Controllers/SiteLayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Umbraco.Web.Mvc;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;

namespace Firstrand.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
            private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Layouts/";

            // Top Layout
            public ActionResult RenderTop()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_head.cshtml");
            }

            // Top Layout
            public ActionResult RenderBanner()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_banner.cshtml");
            }

            // SVG Logo
             public ActionResult RenderLogo()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_logo.svg");
            }
            // Site Menu (Top)
            public ActionResult RenderTopMenu()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_top_menu.cshtml");
            }

            // Header Layout
            public ActionResult RenderHeader()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_header.cshtml");
            }

            // Breadrumb Layout
            public ActionResult RenderBreadcrumb()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_breadcrumb.cshtml");
            }

            // Render the page banner
            public ActionResult RenderPageBanner()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_banner.cshtml");
            }

   
            // Footer Layout
            public ActionResult RenderFooter()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_footer.cshtml");
            }

            // Bottom Layout
            public ActionResult RenderBottom()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_bottom.cshtml");
            }

            // Bottom Layout
            public ActionResult RenderGalleryModal()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_GalleryModal.cshtml");
            }

            // Painting Classrooms Menu
            public ActionResult RenderPaintingClassroomsMenu()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_painting_classrooms_menu.cshtml");
            }
            // Painting Classrooms Menu
            public ActionResult RenderOperatingFranchises()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_operating_franchises.cshtml");
            }
            // Scholarships ticker share bar
            public ActionResult RenderTickerShare()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_tickershare.cshtml");
            }
            // Render the scholarships banner
            public ActionResult RenderScholarshipsBanner()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_banner_scholarships.cshtml");
            }
            // Render the website sidebar
            public ActionResult RenderSidebar()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_sidebar.cshtml");
            }

            // Render the cookies disclaimer html template where required
            public ActionResult RenderCookiesDisclaimer()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "_disclaimer.cshtml");
            }

            // Render the cookies disclaimer html template where required
            public ActionResult RenderInvestorSidebar()
            {
                return PartialView(PARTIAL_VIEW_FOLDER + "/sidebar/investors-sidebar.cshtml");
            }
        }
    }

Controllers/SocietyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;


namespace Firstrand.Controllers
{
    public class SocietyController : SurfaceController
    {
        // Define the route for the partials
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Society/";

        // Render Investor presentations
        public ActionResult RenderSocialInvesting(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_page_social_investing.cshtml");
        }
        // Render Monitoring and evaluations
        public ActionResult RenderMonitoringEvaluations(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_loop_monitoring_and_evaluation.cshtml");
        }
        // Render Firstrand Foundations
        public ActionResult RenderFirstrandFoundations(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_firstrand_foundations.cshtml");
        }
        // Render Firstrand Empowerment fund
        public ActionResult RenderEmpowermentFund(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_empowerment_fund.cshtml");
        }

        // Render the _scholarship_applications partial
        public ActionResult RenderMonitoringAndEvaluation(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_loop_monitoring_and_evaluation.cshtml");
        }
        // Render the scholarships index page
        public ActionResult RenderScholarshipsIndex(){
            return PartialView(PARTIAL_VIEW_FOLDER + "_page_scholarships_index.cshtml");
        }
        // Render the firstrand Volunteers gallery
        public ActionResult RenderFirstrandVolunteers()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_page_firstrand_volunteers.cshtml");
        }
        // Render the firstrand Volunteers single galleries
        public ActionResult RenderSingleGallery()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_loop_galleries.cshtml");
        }


        // Render the firstrand Volunteers single galleries
        public ActionResult RenderPresentations()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "/investors/_loop_presentations.cshtml");
        }
    }
} 

Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Archetype.Extensions;

@*// This template is for the contact page *@


@{
    Layout = null;
}

@{Html.RenderAction("RenderTop", "SiteLayout");}
@{Html.RenderAction("RenderTopMenu", "SiteLayout");}

<!-- /Heading section -->

<header class="jumbotron">
    <div class="map-frame">

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3582.936851263109!2d28.054171315027972!3d-26.100979983483928!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1e95732f26549b3b%3A0x6976238775857e33!2sFirstRand+Bank+Ltd!5e0!3m2!1sen!2s!4v1508344021503"
                width="100%" height="400" frameborder="0" style="border:0" allowfullscreen=""></iframe>
    </div>
</header>

<!-- Page content -->
<section class="container contact">
    
   <div class="row section-heading">
            <div class="col-lg-10 col-md-10">
                <h1 class="heading">
get in <span>touch</span>
                </h1>
                <div class="lead">

                </div>
            </div>
        </div>
    
    

    <div class="">
        <div class="row" style="font-size:12px;">

            <div class="col-md-4">

                <img src="/images/icons/address.png" alt="" class="img-fluid float-left" style="width: 30px;">
    
                      <div class="row mt-2">
                    
                    <div class="col-md-6">
                        
                         
                         <h6>Physical Address</h6>
                    <ul class="list-unstyled">
                        <li> 4 Merchant Place</li>
                        <li> Corner Fredman Drive &</li>
                        <li> Rivonia Road</li>
                        <li> Sandton</li>
                        <li> 2196</li>
                    </ul>
                        
                    </div>
                    <div class="col-md-6">
                        
                         <h6>Postal Address</h6>
                    <ul class="list-unstyled">
                    
                        <li> PO Box 650149</li>
                        <li> Benmore, 2010</li>
                    </ul>
                        
                    </div>
                    
                    
                </div>

              
            </div>

            <div class="col-md-3 border-L">
                <img src="/images/icons/telephone.png" alt="" class="img-fluid float-left" style="width: 30px;">
                <div class="phone row mt-2">
                    
                    <div class="col-md-12">
                        
                         <ul class="list-unstyled">
                        <p><strong>T:</strong><small>+2711 282 1808</small></p>
                        <p><strong>F:</strong><small>+2711 282 8088</small></p>
                    </ul>
                        
                    </div>
                   
                       
                   
                    
                </div>
            </div>

            <div class="col-md-5 border-L">
                <img src="/images/icons/email.png" alt="" class="img-fluid float-left" style="width: 30px;">
                
                <div class="row mt-2">
                    
                    <div class="col-lg-6 col-md-12">
                      <p><strong>Investor relations and media </strong><br><small>transformation@firstrand.co.za</small></p>
                    </ul>
                        
                    </div>
                    <div class="col-lg-6 col-md-12">
                     <p><strong>Investor relations and media </strong><br><small>transformation@firstrand.co.za</small></p>
                    </ul>
                        
                    </div>
                     <div class="col-lg-6 col-md-12">
                       <p><strong>Investor relations and media </strong><br><small>transformation@firstrand.co.za</small></p>
                    </ul>
                        
                    </div>
                    <div class="col-lg-6 col-md-12">
                        
                         <p><strong>Investor relations and media </strong><br><small>transformation@firstrand.co.za</small></p>
                   
                        
                    </div>
                    
                    
                </div>

            </div>



        </div>
    </div>

</section>

@{Html.RenderAction("RenderFooter", "SiteLayout");}
@{Html.RenderAction("RenderBottom", "SiteLayout");}

Views/Default.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "WebBase.cshtml";
}

<!-- Defining page aliases -->
@{
    if (CurrentPage.HasValue("contentGrid"))
    {
        @CurrentPage.GetPropertyValue("contentGrid")
    }
}

Views/Investors.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Firstrand.Controllers;
@using Firstrand.Models;
@using Archetype.Models;
@using Archetype.Extensions;
@{
    Layout = "WebBase.cshtml";
}

<!-- Defining page aliases -->
@{
    if (CurrentPage.HasValue("contentGrid"))
        {
            @CurrentPage.GetPropertyValue("contentGrid")
        }
    }
@{
    var investor_information = Umbraco.Content(2278);
    var financial_results = Umbraco.Content(2299);

    var interim_result_index = Umbraco.Content(1549);
    var year_end_result_index = Umbraco.Content(1553);

    var social_investing = Umbraco.Content(2015);
    var investor_presentations_index = Umbraco.Content(1715);
    var circulors_index = Umbraco.Content(1716);

    var annual_integrated_reporting_index = Umbraco.Content(2388);

    var disclosures_index = Umbraco.Content(1576);
    var report_to_society_index = Umbraco.Content(1566);
    var governance_compliance_index = Umbraco.Content(1588);
    var securitisations_index = Umbraco.Content(1608);
    var environmental_Index = Umbraco.Content(1587);
    var prospectus_index = Umbraco.Content(1598);

    var share_price = Umbraco.Content(1714);
    var key_facts_and_important_dates = Umbraco.Content(1578);
    var credit_ratings = Umbraco.Content(1593);
    var debt_programmes = Umbraco.Content(1604);
    var credit_counterparty = Umbraco.Content(1592);
    var listed_instruments = Umbraco.Content(1603);

    // Render social investing
    if (CurrentPage.IsEqual(social_investing))
    {
        Html.RenderAction("RenderSocialInvesting", "Investors");
    }
    // Render invetor presentations
    else if (CurrentPage.IsEqual(credit_ratings))
    {
        Html.RenderAction("RenderCreditRatings", "Investors");
        Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    }

    else if (CurrentPage.IsEqual(investor_information))
    {
        Html.RenderAction("RenderPresentations", "Investors");
    }

    else if (CurrentPage.IsEqual(financial_results))
    {
        Html.RenderAction("RenderInterimResults", "Investors");
    }

    else if (CurrentPage.IsEqual(annual_integrated_reporting_index))
    {
        Html.RenderAction("RenderAnnualIntegratedReport", "Investors");
    }

    else if (CurrentPage.IsEqual(governance_compliance_index))
    {
        Html.RenderAction("RenderGovernanceCompliance", "Investors");
    }

    else if (CurrentPage.IsEqual(debt_programmes))
    {
        Html.RenderAction("RenderDebtProgrammes", "Investors");
        Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    }

    //else if (CurrentPage.IsEqual(financial_results))
    //{
    //    Html.RenderAction("RenderYearEndResult", "Investors");
    //}

    //else if (CurrentPage.IsEqual(circulors_index))
    //{
    //    Html.RenderAction("RenderCirculars", "Investors");
    //}
    //else if (CurrentPage.IsEqual(disclosures_index))
    //{
    //    Html.RenderAction("RenderDisclosures", "Investors");
    //}
    //else if (CurrentPage.IsEqual(report_to_society_index))
    //{
    //    Html.RenderAction("RenderReportToSociety", "Investors");
    //}
    //else if (CurrentPage.IsEqual(securitisations_index))
    //{
    //    Html.RenderAction("RenderSecuritisations", "Investors");
    //    Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");

    //}
    //else if (CurrentPage.IsEqual(environmental_Index))
    //{
    //    Html.RenderAction("RenderEnvironmentals", "Investors");
    //}
    //else if (CurrentPage.IsEqual(prospectus_index))
    //{
    //    Html.RenderAction("RenderProspectuses", "Investors");
    //    Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    //}
    //else if (CurrentPage.IsEqual(interim_result_index))
    //{
    //    Html.RenderAction("RenderInterimResults", "Investors");
    //}
    //else if (CurrentPage.IsEqual(year_end_result_index))
    //{
    //    Html.RenderAction("RenderYearEndResult", "Investors");
    //}
    //else if (CurrentPage.IsEqual(share_price))
    //{
    //    Html.RenderAction("RenderSharePrice", "Investors");
    //}
    //else if (CurrentPage.IsEqual(key_facts_and_important_dates))
    //{
    //    Html.RenderAction("RenderKey_facts_and_important_dates", "Investors");
    //}

    //else if (CurrentPage.IsEqual(credit_counterparty))
    //{
    //    Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    //}
    //else if (CurrentPage.IsEqual(listed_instruments))
    //{
    //    Html.RenderAction("RenderCookiesDisclaimer", "SiteLayout");
    //}
}

Views/MacroPartials/Reports.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
					  asdfasdf

Views/MacroPartials/_Conference.cshtml
<div class="circle-holder-yellow-class">
    <a href="http://firstrand.onlinereport.co.za/test2018/documents/pdfs/BPC_Conference_Concept.pdf" target="_blank">
        <div class="circle-yellow">
            <div class="circle-yellow-sub class-circle1">
                <h5 class="bigger-h5 wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
                    <span>
                        Conference
                        concept
                    </span>
                </h5>
            </div>
        </div>
    </a>
    <a href="../2017-conference/conference-photos/">
        <div class="circle-yellow">
            <div class="circle-yellow-sub  class-circle2">
                <h5 class="bigger-h5 wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
                    <span>
                        Conference
                        photos
                    </span>
                </h5>
            </div>
        </div>
    </a>
    <a href="../conference-presentations/">
        <div class="circle-yellow">
            <div class="circle-yellow-sub  class-circle3">
                <h5 class="bigger-h5 wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
                    <span>
                        Conference
                        presentations
                    </span>
                </h5>
            </div>
        </div>
    </a>
    <a href="http://firstrand.onlinereport.co.za/test2018/documents/pdfs/BPC_Conference_Concept.pdf" target="_blank">
        <div class="circle-yellow">
            <div class="circle-yellow-sub  class-circle4">
                <h5 class="bigger-h5 wow fadeIn" data-wow-duration="0.5s" data-wow-delay="0.5s">
                    <span>
                        Post
                        conference
                        task
                    </span>
                </h5>
            </div>
        </div>
    </a>
</div>

Views/PageNoSidebar.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Firstrand.Controllers;
@using Firstrand.Models;
@using Archetype.Models;
@using Archetype.Extensions;

@{
    Layout = "WebBase.cshtml";
}

@{Html.RenderAction("RenderFooter", "SiteLayout");}
@{Html.RenderAction("RenderBottom", "SiteLayout");}

Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@Html.Raw(Model.value)

Views/SocietyPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Firstrand.Controllers;
@using Firstrand.Models;
@using Archetype.Models;
@using Archetype.Extensions;
@{
    Layout = "WebBase.cshtml";
}
@{
    if (CurrentPage.HasValue("contentGrid"))
    {
        @CurrentPage.GetPropertyValue("contentGrid")
    }
}

@{
    var page_social_investing = Umbraco.Content(2015);
    var firstrand_foundations = Umbraco.Content(1689);
    var empowerment_fund = Umbraco.Content(1690);
    var monitoring_and_evaluation = Umbraco.Content(1744);
    var scholarships_index = Umbraco.Content(1698);
    var firstrand_volunteers = Umbraco.Content(1241);

    if (CurrentPage.IsEqual(page_social_investing))
    {
        Html.RenderAction("RenderSocialInvesting", "Society");
    }
    if (CurrentPage.IsEqual(firstrand_foundations))
    {
        Html.RenderAction("RenderFirstrandFoundations", "Society");
    }
    if (CurrentPage.IsEqual(empowerment_fund))
    {
        Html.RenderAction("RenderEmpowermentFund", "Society");
    }
    if (CurrentPage.IsEqual(monitoring_and_evaluation))
    {
        Html.RenderAction("RenderMonitoringAndEvaluation", "Society");
    }
    //if (CurrentPage.IsEqual(scholarships_index))
    //{
    //    Html.RenderAction("RenderScholarshipsIndex", "Society");
    //}

    if (CurrentPage.IsEqual(firstrand_volunteers))
    {
        Html.RenderAction("RenderFirstrandVolunteers", "Society");
    }
}

@{ if (@CurrentPage.DocumentTypeAlias == "singleGallery")
    {
    }
}

Views/WebBasePerspectives.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Firstrand.Controllers
@using Firstrand.Models

@*// This template holds all /perspectives sectionS layouts in colab with /Perspectives.cshtml  *@

@{
    Layout = null;

    Html.RenderAction("RenderTop", "SiteLayout");
}

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg main-menu fixed-top navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><img class="logo" src="~/images/logos/logo.png"> </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar"
                aria-controls="Navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="Navbar">
            <ul class="navbar-nav ml-auto mr-lg-5">
                <li class="nav-item none-sm">
                    <a class="nav-link" href="~/the-group/about-firstrand">The group</a>
                </li>
                <li class="nav-item dropdown none-md">
                    <a class="nav-link dropdown-toggle" href="#" id="groupDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        The Group
                    </a>
                    <div class="dropdown-menu" aria-labelledby="groupDropdown">
                        <a class="dropdown-item" href="#">About FirstRand</a>
                        <a class="dropdown-item" href="#">Portfolio of operating businesses</a>
                        <a class="dropdown-item" href="#">Ownership and simplified legal structure</a>
                        <a class="dropdown-item" href="#">Management and board</a>
                        <a class="dropdown-item" href="#">Regional presence and operations in other markets</a>
                        <a class="dropdown-item" href="#">BEE credentials</a>
                    </div>
                </li>
                <li class="nav-item none-sm">
                    <a class="nav-link" href="~/investors/investor-information">Investors</a>
                </li>
                <li class="nav-item dropdown the-group-sm none-md">
                    <a class="nav-link dropdown-toggle" href="#" id="investorsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Investors
                    </a>
                    <div class="dropdown-menu" aria-labelledby="investorsDropdown">
                        <a class="dropdown-item" href="#">Investor information</a>
                        <a class="dropdown-item" href="#">Financial results</a>
                        <a class="dropdown-item" href="#">Integrated reporting</a>
                        <a class="dropdown-item" href="#">SENS</a>
                        <a class="dropdown-item" href="#">Governance</a>
                        <a class="dropdown-item" href="#">Debt programmes</a>
                    </div>
                </li>
                <li class="nav-item none-sm">
                    <a class="nav-link" href="~/society/social-investing">Society</a>
                </li>
                <li class="nav-item dropdown the-group-sm none-md">
                    <a class="nav-link dropdown-toggle" href="#" id="societyDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Society
                    </a>
                    <div class="dropdown-menu" aria-labelledby="societyDropdown">
                        <a class="dropdown-item" href="#">Social investing</a>
                        <a class="dropdown-item" href="#">Foundations</a>
                        <a class="dropdown-item" href="#">firstrand foundation</a>
                        <a class="dropdown-item" href="#">firstrand empowerment foundation</a>
                        <a class="dropdown-item" href="#">monitoring and evaluation</a>
                        <a class="dropdown-item" href="#">Scholarships</a>
                        <a class="dropdown-item" href="#">Firstrand volunteers</a>
                        <a class="dropdown-item" href="#">Beyond painting classrooms</a>
                        <a class="dropdown-item" href="#">Reports</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/perspectives/">Perspectives</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <a class="text-muted" href="#" id="searchToggle">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="mx-3">
                        <circle cx="10.5" cy="10.5" r="7.5"></circle>
                        <line x1="21" y1="21" x2="15.8" y2="15.8"></line>
                    </svg>
                </a>
            </form>
        </div>
    </div>
</nav>
<!-- /Navigation -->

@{
    var Banner = Model.Content.GetPropertyValue<IPublishedContent>("banner");
    var BannerParent = Model.Content.Parent.GetPropertyValue<IPublishedContent>("banner");
    if (CurrentPage.DocumentTypeAlias != "article")
    {
        if (Model.Content.GetPropertyValue<IPublishedContent>("banner") != null)
        {
            <header class="jumbotron">
                <img src="@{ if (Banner != null) {@Banner.Url} else if (BannerParent != null) {@BannerParent.Url}}" class="banner">
            </header>
        }
        else if (BannerParent != null)
        {
            <header class="jumbotron">
                <img src="@{ if (BannerParent != null) {@BannerParent.Url}}" class="banner">
            </header>
        }
        else
        {
            <header class="jumbotron">
                <img src="~/images/banners/perspectives.jpg" class="banner">
            </header>
        }
    }
}

<!-- Page content -->
<section class="page-content">
    <!-- Sidebar -->
    <div class="nav-sidebar">
        <div class="sidebar-sticky @{if (CurrentPage.DocumentTypeAlias == "article") { @("sidebar-perspectives")} else {@(null)} }">
            <h4>Categories</h4>
            <ul class="list-group list-unstyled" id="sidenav">
                <li>
                    <a href="~/perspectives/" class="list-group-item list-group-item-action">
                        All
                    </a>
                </li>
                @{
                    var categories = Model.Content.Site().FirstChild("mainCategory").Children().Where(x => x.IsVisible());
                    var t = 0;
                    foreach (var category in categories.Where("Visible"))
                    {
                        t++;

                        <li>
                            <a href="@category.Url" class="list-group-item list-group-item-action">
                                @category.Name
                            </a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
    <!-- /Sidebar -->
    <div class="container">
        @{if (CurrentPage.DocumentTypeAlias != "article")
            {
                <div class="row">
                    <div class="col-xl-10 col-lg-9 col-md-9 mx-auto">
                        <h1 class="heading">
                            <span>
                                @{ if (CurrentPage.HasValue("title"))
                                    {
                                        @Umbraco.Field("title")
                                    }
                                    else
                                    {
                                        @CurrentPage.Name
                                    }
                                }
                            </span>
                        </h1>
                        <div class="row">
                            <div class="col-lg-8">
                                <p class="lead">
                                    @{ if (CurrentPage.HasValue("lead"))
                                        {
                                            @Html.Raw(@Umbraco.Field("lead"))
                                        }
                                    }
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        <div class="row">
            <div class="@{if (CurrentPage.DocumentTypeAlias == "article") { @("col-xl-12 col-lg-9 col-md-12")} else {@("col-xl-10 col-lg-9 col-md-10 ")} } mx-auto">
                <div class="content">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</section>

@{Html.RenderAction("RenderFooter", "SiteLayout");}
@{Html.RenderAction("RenderBottom", "SiteLayout");}

Views/home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Firstrand.Controllers
@using Firstrand.Models
@using System.Web.Mvc.Html

@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@{@Umbraco.Field("pageName")} - Firstrand</title>

    <!-- Library CSS -->
    <link href="~/css/bootstrap.css" rel="stylesheet">
    <link href="~/modules/animate.css/animate.css" rel="stylesheet">
    <link href="~/modules/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <!-- Main CSS -->
    <link href="~/css/styles.css" rel="stylesheet">
    <link rel="icon" href="~/images/logos/favicon.png">
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body class="frontpage">
    <div id="preloader"></div>

    @{Html.RenderAction("RenderTopMenu", "SiteLayout");}

    <!-- Page Content -->
    @{
        if (CurrentPage.IsEqual(Umbraco.Content("1065")))
        {
            Html.RenderAction("RenderIndex", "Home");
        }
    }
    <!-- /Page Content -->

    @{Html.RenderAction("RenderFooter", "SiteLayout");}
    @{Html.RenderAction("RenderBottom", "SiteLayout");}